### ISSUE TITLE
WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by hugecannon** [dicefm/myriad#9]
panic: sync: WaitGroup is reused before previous Wait has returned

    goroutine 742003 [running]:
    panic(0x657640, 0xc432284a40)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
    sync.(*WaitGroup).Wait(0xc420d9a2c0)
	/usr/local/go/src/sync/waitgroup.go:133 +0xfe
    main.Pool.Do(0xc42f4ca000, 0x7d0, 0xea60, 0x3c, 0xc4200e6300, 0xc4200e6120, 0x13, 0x7d0, 0x3c,             0xc4200e60c0, ...)
	/go/src/github.com/dicefm/myriad/pool.go:38 +0x1f6
    main.Slave.Start(0xc42f4ca000, 0x7d0, 0xea60, 0x3c, 0xc4200e6300, 0xc4200e6120, 0x13, 0x7d0,     0x3c, 0xc4200e60c0, ...)
	/go/src/github.com/dicefm/myriad/slave.go:17 +0x8d
    main.startScenario.func1(0xc420106090)
	/go/src/github.com/dicefm/myriad/http.go:34 +0xed
    created by main.startScenario
	/go/src/github.com/dicefm/myriad/http.go:35 +0x18b`

**Comment by hugecannon** [comment]
Might be resolved by accident with refactor in #10

**Comment by hugecannon** [comment]
Closing for now, haven't seen this since refactor
